name: AI Worker Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ai-worker/**'
      - '.github/workflows/ai-worker-build-and-push.yml'

jobs:
  deploy-ai-worker:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: 'checkout'
        uses: actions/checkout@v2

      - name: Google Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        id: 'setup'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        id: 'docker'
        run: |
          gcloud auth configure-docker ${{ secrets.LOCATION }}-docker.pkg.dev 

      - name: Build and Push AI Worker
        id: 'build-ai-worker'
        run: |
          docker build -t "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/ai-worker:${{ github.sha }}" -t "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/ai-worker:latest" ./ai-worker
          docker push "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/ai-worker" --all-tags

      - name: Deploy AI Worker
        id: 'deploy-ai-worker'
        run: |
          gcloud run deploy reflection-journal-ai-worker \
          --region ${{ secrets.LOCATION }} \
          --image "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/ai-worker:latest" \
          --allow-unauthenticated \
          --min-instances=0 \
          --max-instances=1 \
          --project ${{ secrets.PROJECT_ID }} \
          --set-env-vars="LLM_INFERENCE_URL=${{ secrets.LLM_INFERENCE_URL }},LLM_INFERENCE_API_KEY=${{ secrets.LLM_INFERENCE_API_KEY }},LLM_INFERENCE_MODEL_NAME=${{ secrets.LLM_INFERENCE_MODEL_NAME }}"
