name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: 'checkout'
        uses: actions/checkout@v2

      - name: Google Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        id: 'setup'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        id: 'docker'
        run: |
          gcloud auth configure-docker ${{ secrets.LOCATION }}-docker.pkg.dev 

      - name: Build and Push Backend
        id: 'build-backend'
        run: |
          docker build -t "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/backend:${{ github.sha }}" -t "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/backend:latest" ./backend
          docker push "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/backend" --all-tags

      - name: Build and Push Frontend
        id: 'build-frontend'
        run: |
          docker build -t "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/frontend:${{ github.sha }}" -t "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/frontend:latest" ./frontend
          docker push "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/frontend" --all-tags
          
      - name: Deploy Backend
        id: 'deploy-backend'
        run: |
          gcloud run deploy reflection-journal-backend \
          --region ${{ secrets.LOCATION }} \
          --image "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/backend:latest" \
          --allow-unauthenticated \
          --min-instances=0 \
          --max-instances=1 \
          --project ${{ secrets.PROJECT_ID }} \
          --set-env-vars="OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},DATABASE_URL=sqlite:///db/reflexion.db" \
          --add-volume="name=db,type=cloud-storage,bucket=${{ secrets.BUCKET_NAME }}" \
          --add-volume-mount="volume=db,mount-path=/app/db"

      - name: Deploy Frontend
        id: 'deploy-frontend'
        run: |
          gcloud run deploy reflection-journal-frontend \
          --region ${{ secrets.LOCATION }} \
          --image "${{ secrets.LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/reflection-journal/frontend:latest" \
          --allow-unauthenticated \
          --min-instances=0 \
          --max-instances=1 \
          --project ${{ secrets.PROJECT_ID }}